language: node_js
node_js:
  - 14.15.1

sudo : required
services:
  - docker

before_install:
  - docker build -t jfourdachon/nuxt-quizz -f Dockerfile.dev .

script:
  - docker run -e CI=true jfourdachon/nuxt-quizz npm run test