language: node_js
node_js:
  - 14.11

sudo : required
services:
  - docker

before_install:
  - docker build -t jfourdachon/nuxt-quizz -f Dockerfile.fev ./app/

script:
  - docker run -e CI=true jfourdachon/nuxt-quizz npm run test