# Dockerfile
FROM node:14.15.1-alpine

# create destination directory
RUN mkdir -p /nuxt-app
WORKDIR /nuxt-app

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
COPY . /nuxt-app
RUN yarn
# RUN yarn build    -> production mode

EXPOSE 8500

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=8500

CMD ["yarn", "dev"]
